services:
  postgres:
    image: postgres:18
    container_name: cargo-tracker-db
    environment:
      POSTGRES_USER: cargo
      POSTGRES_PASSWORD: cargo_dev_pw
      POSTGRES_DB: cargotracker
    ports:
      - "5432:5432"
    volumes:
      - cargo-tracker-data:/var/lib/postgresql
  redis:
    image: redis:8
    container_name: cargo-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - cargo-tracker-redis-data:/data

volumes:
  cargo-tracker-data:
  cargo-tracker-redis-data:
